
export const products = [
    {
      name: "Omo1",
      code: "P001",
      metaTitle: "Stylish cafe chair",
      description: "A comfortable and stylish chair for your cafe.",
      price: 250000,
      promotionPrice: 100000,
      includedVAT: true,
      quantity: 10,
      productCategoryId: 1,
      detail: "Made with high-quality materials, perfect for any space.",
      metaKeywords: "chair, cafe, stylish",
      metaDescriptions: "A perfect chair for stylish cafe setups.",
      topHot: true,
      viewCount: 150,
      star: 4.5,
      vote: 120,
      status: true,
      createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
    },
    {
        name: "Omo2",
        code: "P002",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo3",
        code: "P003",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo4",
        code: "P004",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo5",
        code: "P005",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo6",
        code: "P006",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo7",
        code: "P007",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo8",
        code: "P008",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo9",
        code: "P009",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo10",
        code: "P010",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo11",
        code: "P011",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo12",
        code: "P012",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo13",
        code: "P013",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo14",
        code: "P014",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo15",
        code: "P015",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo16",
        code: "P016",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo17",
        code: "P017",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P018",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P019",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P020",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P021",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P022",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P023",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P024",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P025",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P026",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
      {
        name: "Omo",
        code: "P027",
        metaTitle: "Stylish cafe chair",
        description: "A comfortable and stylish chair for your cafe.",
        price: 250000,
        promotionPrice: 100000,
        includedVAT: true,
        quantity: 10,
        productCategoryId: 1,
        detail: "Made with high-quality materials, perfect for any space.",
        metaKeywords: "chair, cafe, stylish",
        metaDescriptions: "A perfect chair for stylish cafe setups.",
        topHot: true,
        viewCount: 150,
        star: 4.5,
        vote: 120,
        status: true,
        createImageProducts: [{ link: "/product.png" }], // Bỏ /public vì Next.js tự tìm trong /public
      },
  ];
  