export const products = [
  {
    name: 'Omo1',
    code: 'P001',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo2',
    code: 'P002',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo3',
    code: 'P003',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo4',
    code: 'P004',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo5',
    code: 'P005',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo6',
    code: 'P006',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo7',
    code: 'P007',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo8',
    code: 'P008',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo9',
    code: 'P009',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo10',
    code: 'P010',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo11',
    code: 'P011',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo12',
    code: 'P012',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo13',
    code: 'P013',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo14',
    code: 'P014',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo15',
    code: 'P015',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo16',
    code: 'P016',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo17',
    code: 'P017',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P018',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P019',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P020',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P021',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P022',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P023',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P024',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P025',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P026',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P027',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P028',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P029',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P030',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P031',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P032',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P033',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P034',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P035',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P036',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P037',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P038',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P039',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P040',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P041',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P042',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P043',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P044',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P045',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P046',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P047',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P048',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P049',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P050',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P051',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P052',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P053',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P054',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P055',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P056',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P057',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P058',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P059',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo',
    code: 'P060',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
];
