export const categories = [
  {
    code: 'cat001',
    name: 'Furniture',
    parentId: 0,
    image: '/product.png',
    link: '/category/5',
    title: 'Shop the Best Furniture',
    detail: 'Explore our latest collection of high-quality furniture.',
    metaDescriptions: 'Buy premium furniture for your home and office.',
    metaKeywords: 'furniture, home decor, chairs, tables',
    status: true,
  },
  {
    code: 'cat002',
    name: 'Bedroom',
    parentId: 0,
    image: '/product.png',
    link: '/category/4',
    title: 'Latest Electronics Collection',
    detail: 'Find the best gadgets and electronic items here.',
    metaDescriptions: 'Shop for high-tech electronics at affordable prices.',
    metaKeywords: 'electronics, gadgets, mobile, laptop',
    status: true,
  },
  {
    code: 'cat003',
    name: 'Bedroom',
    parentId: 0,
    image: '/product.png',
    link: '/category/3',
    title: 'Trending Fashion Apparel',
    detail: 'Discover stylish and comfortable clothing for all seasons.',
    metaDescriptions: 'Buy fashion apparel for men, women, and kids.',
    metaKeywords: 'clothing, fashion, dresses, shirts',
    status: true,
  },
  {
    code: 'cat004',
    name: 'Bedroom',
    parentId: 0,
    image: '/product.png',
    link: '/category/3',
    title: 'Trending Fashion Apparel',
    detail: 'Discover stylish and comfortable clothing for all seasons.',
    metaDescriptions: 'Buy fashion apparel for men, women, and kids.',
    metaKeywords: 'clothing, fashion, dresses, shirts',
    status: false,
  },
  {
    code: 'cat005',
    name: 'Bedroom',
    parentId: 0,
    image: '/product.png',
    link: '/category/3',
    title: 'Trending Fashion Apparel',
    detail: 'Discover stylish and comfortable clothing for all seasons.',
    metaDescriptions: 'Buy fashion apparel for men, women, and kids.',
    metaKeywords: 'clothing, fashion, dresses, shirts',
    status: true,
  },
  {
    code: 'cat006',
    name: 'Bedroom',
    parentId: 0,
    image: '/product.png',
    link: '/category/3',
    title: 'Trending Fashion Apparel',
    detail: 'Discover stylish and comfortable clothing for all seasons.',
    metaDescriptions: 'Buy fashion apparel for men, women, and kids.',
    metaKeywords: 'clothing, fashion, dresses, shirts',
    status: true,
  },
];
