export { default as IEmail } from "./icons/mail.svg";
export { default as IPassword } from "./icons/lock.svg";
export { default as ILogoSignIn } from "./icons/SignIn.svg";
export { default as IFacebook } from "./icons/Facebook.svg";
export { default as IGoogle } from "./icons/google.svg";
export { default as IApple } from "./icons/apple.svg";
export { default as IEye } from "./icons/Eye.svg";
export { default as IEyeOff } from "./icons/EyeClose.svg";
export { default as ITextDel } from "./icons/textdelete.svg";
export { default as IconMenu } from './icons/menu.svg';
export { default as IconClose } from './icons/close.svg';
export { default as IconArrowNext } from './icons/arrow-next.svg';
export { default as IconShoppingCart } from './icons/shoppingcart.svg';
export { default as IconSearch } from './icons/search.svg';
export { default as IconAccount } from './icons/account.svg';
export { default as IconHeart } from './icons/heart.svg';
export { default as IconFiltering } from './icons/filtering.svg'

export { default as Logo } from './images/Frame.png';
export { default as Rectangle } from "./images/Rectangle1.png"