export { default as IEmail } from "./icons/mail.svg";
export { default as IPassword } from "./icons/lock.svg";
export { default as ILogoSignIn } from "./icons/SignIn.svg";
export { default as IFacebook } from "./icons/Facebook.svg";
export { default as IGoogle } from "./icons/google.svg";
export { default as IApple } from "./icons/apple.svg";
export { default as IEye } from "./icons/Eye.svg";
export { default as IEyeOff } from "./icons/EyeClose.svg";
export { default as ITextDel } from "./icons/textdelete.svg";