export const products = [
  {
    name: 'Omo1',
    code: 'P001',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4.5,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo2',
    code: 'P002',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 5,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo3',
    code: 'P003',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 0,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo4',
    code: 'P004',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4.2,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo5',
    code: 'P005',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 2,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo6',
    code: 'P006',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo7',
    code: 'P007',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo8',
    code: 'P008',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo1',
    code: 'P001',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4.5,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo2',
    code: 'P002',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 5,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo3',
    code: 'P003',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 0,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo4',
    code: 'P004',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4.2,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo5',
    code: 'P005',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 2,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo6',
    code: 'P006',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo7',
    code: 'P007',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
  {
    name: 'Omo8',
    code: 'P008',
    metaTitle: 'Stylish cafe chair',
    description: 'A comfortable and stylish chair for your cafe.',
    price: 250000,
    promotionPrice: 100000,
    includedVAT: true,
    quantity: 10,
    productCategoryId: 1,
    detail: 'Made with high-quality materials, perfect for any space.',
    metaKeywords: 'chair, cafe, stylish',
    metaDescriptions: 'A perfect chair for stylish cafe setups.',
    topHot: true,
    viewCount: 150,
    star: 4,
    vote: 120,
    status: true,
    createImageProducts: [{link: '/product.png'}],
  },
];
